module.exports = {
  TOKEN_SECRET:'fe@!§ "ç_"_ç55dg48G5ze.ff#)',
  MONGO_URI: 'localhost',
  MAIN_EMAIL: 'alexismomcilovic@gmail.com',
  MAIN_EMAIL_GOOGLE: 'alexismomcilovic@gmail.com',
  MAIN_EMAIL_GOOGLE_PWD: 'Alexis09',
  COMPANY_NAME:'TTThrthrhrtrtrt',
  URL_HOME:'http://brandcolors.net/',
  COMPANY_DOMAIN:'arbatou.fr',
  PATH_TO_WEBSITE:'../nutrimarketing/',
  PATH_TO_ADMIN:'../MADMIN/',
  GOOGLE_ANALYTICS_ID:'96952362',
  DB_NAME:'test1',
  PORT:'1340',
  DB_USER:'',
  DB_PWD:'',
  REDIS_NAME:'',
  REDIS_PWD:'',
  SESSION_SECRET:'e324cd9190b4ff2b7c4e093de133767b',
  sizequota:3200000000,
  locales:['en', 'es', 'fr', 'de'],
  localesfull: [
    {lang:'fr',langfull:'Francais',langcap:'FR'},
    {lang:'en',langfull:'Anglais',langcap:'EN'},
    {lang:'nl',langfull:'Flamand',langcap:'NL'},
    {lang:'es',langfull:'Espagnol',langcap:'ES'},
  ],
  defaultLocale: 'fr',
};